version: "3.8"

services:
  db:
    image: postgres:15
    container_name: sso_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sso_db

volumes:
  postgres_data:
