"""update model usage log +response time

Revision ID: 27d97975aeb4
Revises: a5cce50b088a
Create Date: 2025-08-02 15:47:21.206153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d97975aeb4'
down_revision: Union[str, Sequence[str], None] = 'a5cce50b088a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_usage_logs', sa.Column('response_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_usage_logs', 'response_time')
    # ### end Alembic commands ###
