"""perbarui tambahkan column squence dan title untuk apikey

Revision ID: 4505de545064
Revises: 4ef6a7eb2374
Create Date: 2025-07-14 14:06:50.605771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4505de545064'
down_revision: Union[str, Sequence[str], None] = '4ef6a7eb2374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('name', sa.String(), nullable=False))
    op.add_column('api_keys', sa.Column('sequence', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'sequence')
    op.drop_column('api_keys', 'name')
    # ### end Alembic commands ###
