"""make colomun name and nickname in tabel users

Revision ID: 451e46fb4023
Revises: 227f9a93524d
Create Date: 2025-07-13 10:01:35.391703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451e46fb4023'
down_revision: Union[str, Sequence[str], None] = '227f9a93524d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
