"""ganti nama column verification typo

Revision ID: 4f054a1efc70
Revises: c1e3c937e26b
Create Date: 2025-07-13 15:13:12.211079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f054a1efc70'
down_revision: Union[str, Sequence[str], None] = 'c1e3c937e26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_verfication_code_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['verification_code'])
    op.drop_column('users', 'verfication_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verfication_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_verfication_code_key'), 'users', ['verfication_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###
