"""verification code column add

Revision ID: c1e3c937e26b
Revises: 451e46fb4023
Create Date: 2025-07-13 13:38:28.091109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e3c937e26b'
down_revision: Union[str, Sequence[str], None] = '451e46fb4023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verfication_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['verfication_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'verfication_code')
    # ### end Alembic commands ###
