"""menambahkan relasi apikey ke apiusagelog

Revision ID: d1464df9b3e6
Revises: adcb282f7cd0
Create Date: 2025-07-14 15:40:58.635855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1464df9b3e6'
down_revision: Union[str, Sequence[str], None] = 'adcb282f7cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
