"""news models update source delete

Revision ID: e23f73893c67
Revises: 998f052b84e7
Create Date: 2025-09-17 11:05:52.029289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23f73893c67'
down_revision: Union[str, Sequence[str], None] = '998f052b84e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
